# Numpy VS PyTorch

## Numpy Array & Torch Tensor

In [1]:
import torch 
import numpy as np

np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

print(np_data, '\n\n', torch_data, '\n\n', tensor2array)

[[0 1 2]
 [3 4 5]] 

 tensor([[0, 1, 2],
        [3, 4, 5]]) 

 [[0 1 2]
 [3 4 5]]


## Math Operations

In [2]:
data = [-1, -2, -3, -4]
tensor = torch.FloatTensor(data) # 32-bit float

print(np.abs(data), '\n\n', torch.abs(tensor), 
      '\n\n', np.sin(data), '\n\n', torch.sin(tensor))

[1 2 3 4] 

 tensor([1., 2., 3., 4.]) 

 [-0.84147098 -0.90929743 -0.14112001  0.7568025 ] 

 tensor([-0.8415, -0.9093, -0.1411,  0.7568])


## Matrix Operations

In [3]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

print(np.matmul(data, data), '\n\n', torch.mm(tensor, tensor))

[[ 7 10]
 [15 22]] 

 tensor([[ 7., 10.],
        [15., 22.]])


In [4]:
data = np.array(data)

print(data.dot(data))

[[ 7 10]
 [15 22]]
