# PyTorch Variable

In PyTorch, `Variable` is **Node** in a computational graph. Unlike TensorFlow, which builds a graph and run many times, PyTorch is **dynamic**, which means that PyTorch builds a new graph everytime it does a forward pass.

In [1]:
import torch
from torch.autograd import Variable

tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)

print(tensor, '\n\n', variable, 
     '\n\n', tensor * tensor, '\n\n', variable * variable)

tensor([[1., 2.],
        [3., 4.]]) 

 tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 

 tensor([[ 1.,  4.],
        [ 9., 16.]]) 

 tensor([[ 1.,  4.],
        [ 9., 16.]], grad_fn=<MulBackward0>)


In [2]:
t_out = torch.mean(tensor * tensor)
v_out = torch.mean(variable * variable)

print(t_out, '\n\n', v_out)

tensor(7.5000) 

 tensor(7.5000, grad_fn=<MeanBackward0>)


We can interpret $v\_out$ as $Loss$, and $variable$ as $W$, and then use backpropagation to compute $\nabla_{W}L$:

In [3]:
v_out.backward()

# v_out = 1/4 * sum(variable * variable)
# d(v_out)/d(variable) = 1/4 * 2 * varible = variable/2
print(variable.data, # variable.data is a tensor, and we can convert it into numpy array using variable.data.numpy()
      '\n\n', variable.grad)

tensor([[1., 2.],
        [3., 4.]]) 

 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
